CREATE TABLE COMPANIES(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE CUSTOMERS(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE SKILLS(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  type ENUM('Java', 'C++', 'HTML/CSS', 'JavaScript', 'Python', 'RubyOnRails', 'SQL', 'Golang', 'R', 'C#', 'F#')
);

CREATE TABLE PROJECTS(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  company_id INT NOT NULL,
  customer_id INT NOT NULL,
  FOREIGN KEY (company_id) REFERENCES COMPANIES(id),
  FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id)
);

CREATE TABLE DEVELOPERS(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(50),
  project_id int,
  company_id int NOT NULL,
  FOREIGN KEY (company_id) REFERENCES COMPANIES(id),
  FOREIGN KEY (project_id) REFERENCES PROJECTS(id)
);

CREATE TABLE DEVELOPER_SKILLS(
  dev_id INT NOT NULL,
  skill_id INT NOT NULL,
  FOREIGN KEY (dev_id) REFERENCES DEVELOPERS(id),
  FOREIGN KEY (skill_id) REFERENCES SKILLS(id)
);